#!/bin/zsh

install_yay() {
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
    cd ..
    rm yay -rf
}

install_norman() {
    git clone https://github.com/norman-pkgs/norman.git
    cd norman
    ./AUTOINSTALL
    cd ..
    rm norman -rf
}

[[ $(which yay) == "yay not found" ]] && install_yay
[[ $(which norman) == "norman not found" ]] && install_norman
[[ $(which autoinstall) == "autoinstall not found" ]] && install_norman
